### ISSUE TITLE
Fails to start with custom configuration (using stable/postgresql helm chart)

### ISSUE THREAD

**Issue by bootc** [bitnami/bitnami-docker-postgresql#101]
**Description**

When using the `stable/postgresql` Helm chart (3.7.1) and custom configuration, PostgreSQL fails to start. This is with setting custom configuration using `postgresqlConfiguration`.

**Steps to reproduce the issue:**

```sh
helm install stable/postgresql \
  --set postgresqlConfiguration.max_connections=200
```

**Describe the results you received:**

The log contains:

```
INFO  ==> Starting postgresql... 
nami    ERROR Unable to start com.bitnami.postgresql: pg_ctl: could not start server
Examine the log output.
```

**Describe the results you expected:**

PostgreSQL should start. :-)

**Additional information you deem important (e.g. issue happens only occasionally):**

Appears to be reliably reproducible on both 10.6.0 and 9.6.11 PostgreSQL versions.

**Version**

- Output of `docker version`:

```
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:23:18 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:22:21 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```

- Output of `docker info`:

[probably not relevant, but let me know and I'll include it]

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

This is a bare-metal Kubernetes cluster built with RKE. Kubernetes 1.12.3.

My *suspicion* is that when the startup scripts copy the postgresql.conf from the mounted `ConfigMap`, it copies the symlink to the versioned configuration rather than the target, and thus it copies a dangling symlink. I haven't been able to confirm this, though.

**Comment by bootc** [comment]
I should add that I used a sidecar container to pull the logs out and PostgreSQL was complaining:

```
postgres: could not access the server configuration file "/opt/bitnami/postgresql/conf/postgresql.conf": No such file or directory
```

**Comment by andresbono** [comment]
Hi @bootc, thanks for reporting this issue. We'll investigate it and we'll get back to you.

Thanks again!

**Comment by marcosbc** [comment]
Hi @bootc, we fixed the issue in the Bitnami PostgreSQL container's side. You can try it on your side by updating the container version in your chart to the latest release.

**Comment by bootc** [comment]
Hi @marcosbc, I can confirm that `docker.io/bitnami/postgresql:9.6.11-r42` works for me now, thanks.

**Comment by erdarun** [comment]
@marcosbc Issue not yet resolved. We are facing the same issue for the latest helm chart version 3.11.7 app version 10.7.0.

**Comment by andresbono** [comment]
Hi @erdarun, thanks for notifying. Let's continue in #114.
