### ISSUE TITLE
Does bitnami docker postgresql support ICU collation?

### ISSUE THREAD

**Issue by ajoyej** [bitnami/bitnami-docker-postgresql#140]
Hello,
We have the need of using the ICU collation within our postgresql.
Is the image supports the ICU collation?

If not, what are the options to have it supported?

Thanks,
José

**Comment by miguelaeh** [comment]
Hi @ajoyej ,
At this moment our image is not build to support ICU.
To support ICU PostgreSQL must be build in a specific way (using specific parameters), so I will create an internal task to evaluate if we should include this in our image.
You can obtain more information in the following link:
https://www.2ndquadrant.com/en/blog/icu-support-postgresql-10/

Thank for your reporting, I will ping you when we evaluate this.

**Comment by tompizmor** [comment]
Hi @ajoyej,

We have just released new versions of the PostgreSQL image with ICU support. Can you pull the latest image and give it a try?

You can check the configure options with this command:

```
$ pg_config --configure
'--prefix=/opt/bitnami/postgresql' '--with-libedit-preferred' '--with-openssl' '--with-libxml' '--with-libxslt' '--with-readline' '--with-icu' 'CC=gcc' 'CFLAGS=-s' 'LDFLAGS=-Wl,-rpath=/opt/bitnami/postgresql/lib -L/opt/bitnami/postgresql/lib' 'CPPFLAGS=-I/opt/bitnami/postgresql/include'
```

As you can see, it has been compiled with the `--with-icu` flag.

**Comment by ajoyej** [comment]
Hello,

Sound great!
I tried to install it using our helm chart. However, we still have a version 3.x of helm and just changing the postgresql version to the one you just release does not work... I first need to migrate the chart to 5 first....
This is a bit of work since we have extended it to fit our special needs.

I will try to do it and let you know when I'm done with it

Thanks
José

**Comment by tompizmor** [comment]
> I tried to install it using our helm chart. However, we still have a version 3.x of helm and just changing the postgresql version to the one you just release does not work... I first need to migrate the chart to 5 first....

Yes, I am afraid that the current PostgreSQL image is not compatible with the chart version 3.X.
